services:
  sr2-edi:
    build: .
    container_name: sr2-edi
    restart: unless-stopped
    networks:
      - sr2
    volumes:
      - ./.dockervols/edi/:/home/workspace
      - ./configs:/app/configs
    environment:
      PORT: 8008


  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3000:8080"
    networks:
      - sr2
    environment:
      OLLAMA_API_BASE_URL: ""
      OPENAI_API_BASE_URL: http://sr2-edi:8008/v1
      OPENAI_API_KEY: "sr2"
      WEBUI_AUTH: "false"
    volumes:
      - ./.dockervols/open-webui:/app/backend/data
    depends_on:
      - sr2-edi

  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11435:11434"
    networks:
      - sr2
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
      - 993
    environment:
      HIP_VISIBLE_DEVICES: 0
      ROCR_VISIBLE_DEVICES: 0
      ROCM_MLIR_ENABLE_DYNAMIC_SHAPING: 1
      HSA_OVERRIDE_GFX_VERSION: 11.0.0
      OLLAMA_FLASH_ATTENTION: 1
      OLLAMA_KEEP_ALIVE: 15m
      OLLAMA_KV_CACHE_TYPE: q8_0
      OLLAMA_CONTEXT_LENGTH: 32768
      OLLAMA_MAX_LOADED_MODELS: 2
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    deploy:
      resources:
        reservations:
          devices:
            - driver: amd
              count: 1
              capabilities: [gpu]
    env_file:
      - path: /etc/docker/secrets/${COMPOSE_PROJECT_NAME}/.env

  ollama-exporter:
    image: ghcr.io/norskhelsenett/ollama-metrics:latest
    container_name: ollama-exporter
    networks:
      - sr2
    environment:
      - OLLAMA_HOST=http://ollama:11434
    ports:
      - "11434:8080"
    depends_on:
      - ollama

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "${UID}:${GID}"
    volumes:
      - ./o11y/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./.dockervols/prometheus:/prometheus
    networks:
      - sr2
    depends_on:
      - ollama-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "${UID}:${GID}"
    ports:
      - "3080:3000"
    networks:
      - sr2
    volumes:
      - ./.dockervols/grafana:/var/lib/grafana:rw
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    environment:
      POSTGRES_USER: sr2
      POSTGRES_PASSWORD: sr2
      POSTGRES_DB: sr2
    networks:
      - sr2
    volumes:
      - ./.dockervols/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sr2"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  web:
    external: false
  sr2:
    external: false
